[package]
name = "cetk"
version = "0.1.0"
edition = "2024"

[dependencies]
claudius = { path = "../claudius", version = "0.11.0" }
libc = "0.2.174"
one_two_eight = "0.9.0"
chromadb = { path = "rust-client" }
serde = "1.0.219"
serde_json = "1.0.141"
utf8path = "0.9.1"

[dev-dependencies]
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
