name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - uses: arduino/setup-protoc@v3
    - name: cargo clippy
      run: cargo clippy --all-targets -- -D clippy::all -D warnings
    - name: cargo test
      run: cargo test
      env:
        CHROMA_API_KEY: ${{ secrets.CHROMA_API_KEY }}
